// Generated by jextract

package com.whichlicense.metadata.identification.license.panama.internal;

import java.lang.foreign.MemorySegment;
import java.lang.foreign.SegmentScope;

/**
 * {@snippet :
 * char* (*CNormalizationFn)(char*);
 *}
 */
@FunctionalInterface
public interface CNormalizationFn {
    static MemorySegment allocate(CNormalizationFn fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(constants$0.CNormalizationFn_UP$MH, fi, constants$0.CNormalizationFn$FUNC, scope);
    }

    MemorySegment apply(MemorySegment _x0);
}
